package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"

	"github.com/mandelsoft/filepath/pkg/filepath"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

var caser = cases.Title(language.AmericanEnglish)

func comment(s string, l int) []byte {
	return []byte(fmt.Sprintf(fmt.Sprintf("<!-- %%-%ds -->\n", l), s))
}

func generate(files []*File, resolution Resolution, source, target string, opts Options) error {
	for _, f := range files {
		if filepath.Base(f.relpath) == "_definitions.md" {
			continue
		}
		tgt := filepath.Join(target, f.relpath)
		src := filepath.Join(source, f.relpath)
		rf, err := os.Open(src)
		if err != nil {
			return fmt.Errorf("cannot read source %s", src, err)
		}
		var r io.Reader = rf

		os.MkdirAll(filepath.Dir(tgt), 0o766)
		w, err := os.OpenFile(tgt, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
		if err != nil {
			rf.Close()
			return fmt.Errorf("cannot read source %s", src, err)
		}
		var header []byte
		if strings.HasSuffix(f.relpath, ".md") {
			rel, err := filepath.Rel(filepath.Dir(tgt), src)
			l := len(rel) + 5
			if l < 31 {
				l = 31
			}
			header = comment("DO NOT MODIFY", l)
			header = append(header, comment("this file is generated by mdref", l)...)
			if err == nil && !opts.SkipSource {
				header = append(header, comment(fmt.Sprintf("from %s", rel), l)...)
			}
			header = append(header, []byte("\n")...)

			var win bool

			if !f.HasSubst() {
				var err error
				var data []byte

				data, err = io.ReadAll(rf)
				if err == nil {
					data, win = normalizeLineEndings(data)
					data = append(header, data...)

					data = toLineEndings(data, win, opts)
					r = bytes.NewReader(data)
				}

				if err == nil {
					_, err = io.Copy(w, r)
				}
				rf.Close()
				w.Close()
				if err != nil {
					return fmt.Errorf("cannot read source %s", src, err)
				}
			} else {
				data, err := io.ReadAll(r)
				if err != nil {
					rf.Close()
					w.Close()
					return fmt.Errorf("cannot read source %s", src, err)
				}
				data, win = normalizeLineEndings(data)
				if opts.Unix {
					win = false
				}
				if opts.Windows {
					win = true
				}
				for k := range f.terms {
					ref, term := resolution.Resolve(k, f.relpath)

					data = substituteTerm(data, k, `{{{%s}}}`, term, "%s")
					data = substituteTerm(data, k, `[{{%s}}]`, term, fmt.Sprintf("[%%s](%s)", ref))
				}

				for k := range f.refs {
					ref, _ := resolution.Resolve(k, f.relpath)
					data = substituteTerm(data, k, `({{%s}})`, nil, fmt.Sprintf("(%s)", ref), false)
				}

				for k, r := range f.targets {
					if r.generate {
						data = bytes.ReplaceAll(data, r.Raw(), []byte("<a id=\""+k+"\"></a>"))
						// exp := regexp.MustCompile("{{" + k + "(:[a-zA-Z][a-zA-Z0-9- ]+)?}}")
						// data = exp.ReplaceAll(data, []byte(`<a id="`+k+`"></a>`))
					} else {
						data = bytes.ReplaceAll(data, r.Raw(), []byte{})
						// exp := regexp.MustCompile("{{" + k + "(:[a-zA-Z][a-zA-Z0-9- ]+)?}}\n?")
						// data = exp.ReplaceAll(data, []byte(""))
					}
				}

				for k, c := range f.commands {
					exp := regexp.MustCompile(regexp.QuoteMeta(k))
					sub, err := c.GetSubstitution(src, opts)
					if err != nil {
						return fmt.Errorf("%s: %s: %s; %w", f.relpath, c.Position(), k, err)
					}
					if len(sub) > 0 && c.EOL() && sub[len(sub)-1] == '\n' {
						sub = sub[:len(sub)-1]
					}
					data = exp.ReplaceAll(data, sub)
				}

				data = append(header, data...)
				_, err = w.Write(toLineEndings(data, win, opts))
				rf.Close()
				w.Close()
				if err != nil {
					return fmt.Errorf("cannot write target %s: %w", tgt, err)
				}
			}
		}
	}
	return nil
}

func formatTerm(msg, term string) string {
	if strings.Contains(msg, "%s") {
		return fmt.Sprintf(msg, term)
	}
	return msg
}

func substituteTerm(data []byte, key string, kformat string, term *Ref, tformat string, flavors ...bool) []byte {
	data = bytes.ReplaceAll(data, []byte(fmt.Sprintf(kformat, key)), []byte(formatTerm(tformat, term.AsFormatted())))

	if len(flavors) == 0 || flavors[0] {
		data = bytes.ReplaceAll(data, []byte(fmt.Sprintf(kformat, "*"+key)), []byte(formatTerm(tformat, term.AsPlural())))

		t := term.AsUpper()
		key = strings.ToUpper(key[:1]) + key[1:]

		data = bytes.ReplaceAll(data, []byte(fmt.Sprintf(kformat, key)), []byte(formatTerm(tformat, term.Format(t))))
		data = bytes.ReplaceAll(data, []byte(fmt.Sprintf(kformat, "*"+key)), []byte(formatTerm(tformat, term.Plural(t))))
	}

	return data
}
